/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rippling.smithy;

import java.io.File;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void canConvertModel() {
        final String json = App.convertModel(new File(getClass().getResource("model.json").getFile()));
        assertNotNull(json, "json should not be null");
    }
}
 
